<?php

namespace Shortly;

require_once dirname(__FILE__) . '/../../src/App.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-05 at 04:50:30.
 */
class AppTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var App
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new App;
        $_SERVER = array();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Shortly\App::start
     * @todo   Implement testStart().
     */
    public function testStart() {
        header('Location : http://foo.com');
        $_SERVER["REQUEST_METHOD"] = "GET";
        $this->assertTrue(method_exists($mydb, "getAll"));
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
