<?php

namespace Shortly;

require_once dirname(__FILE__) . '/../../src/App.php';
require_once dirname(__FILE__) . '/../../src/Api.php';
require_once dirname(__FILE__) . '/../../src/MyDB.php';
require_once dirname(__FILE__) . '/../../src/Generator.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-05 at 04:50:30.
 */
class AppTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var App
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        copy(dirname(__FILE__) . "/../shortlyTest.db", dirname(__FILE__) . "/../test.db");
        MyDB::getInstance(dirname(__FILE__) . "/../test.db");   
        $this->object = new App;
        $_SERVER = array();
        $_SERVER["HTTP_HOST"] = "short.ly";
        $_POST = array();
        $_POST["url"] = "m.bbc.com";
        $_POST["device"]="Mobile";
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Shortly\App::start
     * @todo   Implement testStart().
     */
    public function testStart() {
        ob_start();
        $_SERVER["REQUEST_METHOD"] = "GET";
        $data = $this->object->start();
        $content = ob_get_contents();
        $this->assertEquals('{"status":"success","data":[]}', $content);
        ob_flush();
        $_SERVER["REQUEST_METHOD"] = "POST";
        $data = $this->object->start();
        $content = ob_get_contents();
        $this->assertRegExp('/^.+success.+$/', $content);
        ob_end_clean();
    }

}
