<?php

namespace Shortly;

require_once dirname(__FILE__) . '/../../src/Generator.php';
require_once dirname(__FILE__) . '/../../src/MyDb.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-05 at 04:50:40.
 */
class GeneratorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Generator
     */
    protected $object;
    private $connection;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->connection = MyDB::getInstance(dirname(__FILE__) . "/../shortlyTest.db");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Shortly\Generator::getUniqueID
     */
    public function testGetUniqueID() {
        $ts = time();
        $this->assertTrue(strlen(Generator::getUniqueID($ts)) > 0);
        $this->assertFalse(Generator::getUniqueID($ts) === Generator::getUniqueID($ts));
        
    }

}
