<?php

namespace Shortly;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-05 at 04:50:48.
 */
class MyDBTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var MyDB
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MyDB;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Shortly\MyDB::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shortly\MyDB::getAll
     * @todo   Implement testGetAll().
     */
    public function testGetAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shortly\MyDB::getUrl
     * @todo   Implement testGetUrl().
     */
    public function testGetUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shortly\MyDB::post
     * @todo   Implement testPost().
     */
    public function testPost() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shortly\MyDB::put
     * @todo   Implement testPut().
     */
    public function testPut() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Shortly\MyDB::getDeviceId
     * @todo   Implement testGetDeviceId().
     */
    public function testGetDeviceId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
