<?php

namespace Shortly;

require_once dirname(__FILE__) . '/../../src/Utils.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-10-05 at 04:50:02.
 */
class UtilsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Utils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Shortly\Utils::getDeviceType
     */
    public function testGetDeviceType() {
        $this->assertEquals("Desktop", Utils::getDeviceType());
    }

}
